In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('../../dataset/meal_service/train.csv')

In [3]:
df_train.head()

,일자,요일,본사정원수,본사휴가자수,본사출장자수,본사시간외근무명령서승인건수,현본사소속재택근무자수,조식메뉴,중식메뉴,석식메뉴,중식계,석식계
0,2016-02-01,월,2601,50,150,238,0.0,모닝롤/찐빵 우유/두유/주스 계란후라이 호두죽/쌀밥 (쌀:국내산) 된장찌개 쥐...,"쌀밥/잡곡밥 (쌀,현미흑미:국내산) 오징어찌개 쇠불고기 (쇠고기:호주산) 계란찜 ...","쌀밥/잡곡밥 (쌀,현미흑미:국내산) 육개장 자반고등어구이 두부조림 건파래무침 ...",1039.0,331.0
1,2016-02-02,화,2601,50,173,319,0.0,모닝롤/단호박샌드 우유/두유/주스 계란후라이 팥죽/쌀밥 (쌀:국내산) 호박젓국찌...,"쌀밥/잡곡밥 (쌀,현미흑미:국내산) 김치찌개 가자미튀김 모둠소세지구이 마늘쫑무...","콩나물밥*양념장 (쌀,현미흑미:국내산) 어묵국 유산슬 (쇠고기:호주산) 아삭고추무...",867.0,560.0
2,2016-02-03,수,2601,56,180,111,0.0,모닝롤/베이글 우유/두유/주스 계란후라이 표고버섯죽/쌀밥 (쌀:국내산) 콩나물국...,"카레덮밥 (쌀,현미흑미:국내산) 팽이장국 치킨핑거 (닭고기:국내산) 쫄면야채무침 ...","쌀밥/잡곡밥 (쌀,현미흑미:국내산) 청국장찌개 황태양념구이 (황태:러시아산) 고기...",1017.0,573.0
3,2016-02-04,목,2601,104,220,355,0.0,"모닝롤/토마토샌드 우유/두유/주스 계란후라이 닭죽/쌀밥 (쌀,닭:국내산) 근대국...","쌀밥/잡곡밥 (쌀,현미흑미:국내산) 쇠고기무국 주꾸미볶음 부추전 시금치나물 ...","미니김밥*겨자장 (쌀,현미흑미:국내산) 우동 멕시칸샐러드 군고구마 무피클 포...",978.0,525.0
4,2016-02-05,금,2601,278,181,34,0.0,모닝롤/와플 우유/두유/주스 계란후라이 쇠고기죽/쌀밥 (쌀:국내산) 재첩국 방...,"쌀밥/잡곡밥 (쌀,현미흑미:국내산) 떡국 돈육씨앗강정 (돼지고기:국내산) 우엉잡채...","쌀밥/잡곡밥 (쌀,현미흑미:국내산) 차돌박이찌개 (쇠고기:호주산) 닭갈비 (닭고기:...",925.0,330.0

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   일자              1205 non-null   object
 1   요일              1205 non-null   object
 2   본사정원수           1205 non-null   int64
 3   본사휴가자수          1205 non-null   int64
 4   본사출장자수          1205 non-null   int64
 5   본사시간외근무명령서승인건수  1205 non-null   int64
 6   현본사소속재택근무자수     1205 non-null   float64
 7   조식메뉴            1205 non-null   object
 8   중식메뉴            1205 non-null   object
 9   석식메뉴            1205 non-null   object
 10  중식계             1205 non-null   float64
 11  석식계             1205 non-null   float64
dtypes: float64(3), int64(4), object(5)
memory usage: 113.1+ KB

In [5]:
df_test = pd.read_csv('../../dataset/meal_service/test.csv')

In [6]:
df_test.head()
# 조식 반찬 개수: 7
# 중식 반찬 개수: 6 (디저트 없음) or 7 (디저트 있음)
# 석식 반찬 개수: 6

# 조식 메뉴 포맷:  
# 중식 메뉴 포맷: 밥 - 국 - 반찬 3 - (요구르트) - 김치 - (디저트)
# 석식 메뉴 포맷: 밥 - 국 - 반찬 3 - 김치

,일자,요일,본사정원수,본사휴가자수,본사출장자수,본사시간외근무명령서승인건수,현본사소속재택근무자수,조식메뉴,중식메뉴,석식메뉴
0,2021-01-27,수,2983,88,182,5,358.0,모닝롤/연유버터베이글 우유/주스 계란후라이/찐계란 단호박죽/흑미밥 우거지국 고기완자...,쌀밥/흑미밥/찰현미밥 대구지리 매운돈갈비찜 오꼬노미계란말이 상추무침 포기김치 양상추...,흑미밥 얼큰순두부찌개 쇠고기우엉볶음 버섯햄볶음 (New)아삭이고추무절임 포기김치
1,2021-01-28,목,2983,104,212,409,348.0,모닝롤/대만샌드위치 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 황태국 시래기지짐 ...,쌀밥/보리밥/찰현미밥 우렁된장찌개 오리주물럭 청양부추전 수제삼색무쌈 겉절이김치 양상...,충무김밥 우동국물 오징어무침 꽃맛살샐러드 얼갈이쌈장무침 석박지
2,2021-01-29,금,2983,270,249,0,294.0,모닝롤/핫케익 우유/주스 계란후라이/찐계란 오곡죽/흑미밥 매생이굴국 고구마순볶음 양...,쌀밥/흑미밥/찰현미밥 팽이장국 수제돈까스*소스 가자미조림 동초나물무침 포기김치 양상...,흑미밥 물만둣국 카레찜닭 숯불양념꼬지어묵 꼬시래기무침 포기김치
3,2021-02-01,월,2924,108,154,538,322.0,모닝롤/촉촉한치즈케익 우유/주스 계란후라이/찐계란 누룽지탕/흑미밥 두부김칫국 새우완...,쌀밥/흑미밥/찰현미밥 배추들깨국 오리대패불고기 시금치프리타타 부추고추장무침 포기김치...,흑미밥 동태탕 돈육꽈리고추장조림 당면채소무침 모자반무침 포기김치
4,2021-02-02,화,2924,62,186,455,314.0,모닝롤/토마토샌드 우유/주스 계란후라이/찐계란 채소죽/흑미밥 호박맑은국 오이생채 양...,쌀밥/팥밥/찰현미밥 부대찌개 닭살데리야끼조림 버섯탕수 세발나물무침 알타리김치/사과푸...,흑미밥 바지락살국 쇠고기청경채볶음 두부구이*볶은김치 머위된장무침 백김치

In [7]:
df_sample = pd.read_csv('../../dataset/meal_service/sample_submission.csv')

In [8]:
df_sample.head()

           일자  중식계  석식계
0  2021-01-27    0    0
1  2021-01-28    0    0
2  2021-01-29    0    0
3  2021-02-01    0    0
4  2021-02-02    0    0

In [9]:
df_train.describe()

,본사정원수,본사휴가자수,본사출장자수,본사시간외근무명령서승인건수,현본사소속재택근무자수,중식계,석식계
count,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000,1205.000000
mean,2807.815768,157.913693,241.142739,274.117012,43.506224,890.334440,461.772614
std,171.264404,144.190572,43.532298,246.239651,109.937400,209.505057,139.179202
min,2601.000000,23.000000,41.000000,0.000000,0.000000,296.000000,0.000000
25%,2645.000000,71.000000,217.000000,4.000000,0.000000,758.000000,406.000000
50%,2760.000000,105.000000,245.000000,299.000000,0.000000,879.000000,483.000000
75%,2962.000000,185.000000,272.000000,452.000000,0.000000,1032.000000,545.000000
max,3305.000000,1224.000000,378.000000,1044.000000,533.000000,1459.000000,905.000000

In [10]:
df_test.describe()
# 결측치 없음, 중식계 + 석식계 예측해야함

             본사정원수      본사휴가자수      본사출장자수  본사시간외근무명령서승인건수  현본사소속재택근무자수
count    50.000000   50.000000   50.000000       50.000000    50.000000
mean   2956.840000  129.520000  209.220000      380.140000   298.140000
std      24.968846   84.065873   39.454593      346.564304    52.058056
min    2924.000000   50.000000  131.000000        0.000000   179.000000
25%    2924.000000   78.250000  176.500000        1.000000   257.250000
50%    2974.000000   95.000000  202.500000      465.500000   300.000000
75%    2975.000000  137.500000  245.250000      681.000000   333.250000
max    2983.000000  489.000000  279.000000     1003.000000   413.000000

In [11]:
breakfast_menus = []

for menu in df_train['조식메뉴']:
    menu_split = menu.split(' ')

    menu_list = []
    for dish in menu_split:
        if len(dish) > 1:
            if dish[1] == 'N':
                # (New) 제거
                menu_list.append(dish.split(')')[1])
            elif dish[0] != '(' and dish[-1] != ')' :
                # 원산지 제거
                menu_list.append(dish)
    if len(menu_list) > 3:
        breakfast_menus.append(menu_list) 
    else:
        breakfast_menus.append(['*'])

In [12]:
lunch_menus = []

for menu in df_train['중식메뉴']:
    menu_split = menu.split(' ')

    menu_list = []
    for dish in menu_split:
        if len(dish) > 1:
            if dish[1] == 'N':
                # (New) 제거
                menu_list.append(dish.split(')')[1])
            elif dish[0] != '(' and dish[-1] != ')' :
                # 원산지 제거
                menu_list.append(dish)
    if len(menu_list) > 3:
        lunch_menus.append(menu_list) 
    else:
        lunch_menus.append(['*'])

In [13]:
dinner_menus = []

for menu in df_train['석식메뉴']:
    menu_split = menu.split(' ')

    menu_list = []
    for dish in menu_split:
        if len(dish) > 1:
            if dish[1] == 'N':
                # (New) 제거
                menu_list.append(dish.split(')')[1])
            elif dish[0] != '(' and dish[-1] != ')' :
                # 원산지 제거
                menu_list.append(dish)
    if len(menu_list) > 3:
        dinner_menus.append(menu_list) 
    else:
        dinner_menus.append(['*'])

In [18]:
dish_cnt = {}
for menu in dinner_menus:
    if len(menu) == 1:
        continue
    else:
        if menu[1] not in dish_cnt:
            dish_cnt[menu[1]] = 1
        else:
            dish_cnt[menu[1]] = dish_cnt[menu[1]] + 1
print(dish_cnt)

{'육개장': 29, '어묵국': 18, '청국장찌개': 20, '우동': 23, '차돌박이찌개': 13, '맑은국': 33, '김치콩나물국': 2, '홍합미역국': 1, '된장찌개': 30, '순두부찌개': 19, '설렁탕': 8, '옹심이만두국': 4, '콩비지찌개': 21, '열무된장국': 18, '잔치국수': 38, '닭개장': 23, '버섯들깨탕': 3, '오징어국': 11, '대구찌개': 3, '가쯔오장국': 29, '짬뽕': 13, '연두부탕': 10, '달래된장찌개': 1, '계란파국': 10, '뼈해장국': 4, '양송이스프': 4, '닭곰탕': 9, '수제비국': 10, '알탕': 8, '미소장국': 28, '냉이된장찌개': 1, '유부장국': 21, '쇠고기미역국': 8, '매운버섯국': 10, '쇠고기무국': 11, '유부주머니국': 9, '팽이버섯장국': 1, '들깨미역국': 4, '꽃게탕': 10, '팽이버섯국': 1, '비빔메밀국수': 1, '들깨버섯탕': 3, '북어국': 2, '부대찌개*라면사리': 3, '가쯔오국': 5, '팽이장국': 10, '해물순두부찌개': 4, '쌀국수': 20, '시래기국': 10, '열무물국수': 2, '냉모밀국수': 8, '소고기미역국': 3, '호박잎찌개': 1, '비빔국수': 1, '토마토스파게티': 2, '김치찌개': 6, '계란국': 10, '김치말이국수': 9, '차돌박이된장찌개': 2, '시금치국': 6, '함박스테이크': 1, '부대찌개': 25, '쇠고기샤브국': 18, '물냉면': 2, '느타리버섯국': 2, '동태찌개': 4, '돈육김치찌개': 11, '콩가루배추국': 9, '아욱국': 9, '콩나물국': 20, '짬뽕수제비국': 1, '콩국수': 5, '스파게티/크림스프': 1, '김치우동': 9, '무채국': 7, '감자국': 9, '작은밥': 2, '콩나물냉국': 1, '로제파스타/스프': 2, '얼갈이된장국': 9, '참치김치찌개': 11, '고추장찌개': 13, '꼬지어묵우동': 2, '무채맑은국': 1, '조갯살미역국': 1, '근대된장국': 1, '황태국': 7, '어묵우동': 5, '해물된장찌개': 10, '참치주먹밥': 1, '옥수수스프': 3, '북어계란국': 5, '바지락수제비': 4, '해물짬뽕': 1, '목살김치찌개': 1, '시금치된장국': 5, '매운감자국': 1, '대구지리': 2, '매생이굴국': 1, '미역국': 8, '봄동된장국': 2, '매운오징어국': 1, '감자찌개': 1, '들깨무채국': 1, '뼈감자탕': 9, '새우튀김우동': 7, '쇠고기매운국': 1, '시래기들깨탕': 1, '장국': 1, '소고기무국': 12, '사골우거지국': 1, '미역장국': 6, '꼬치어묵탕': 2, '김치두부국': 4, '우거지탕': 1, '유부우동': 1, '매운어묵국': 1, '카레돈까스정식': 1, '야채볶음밥': 1, '옛날돈가스': 3, '배추된장국': 10, '연두부찌개': 2, '우거지해장국': 2, '단호박스프': 5, '새알만두국': 1, '감자고추장찌개': 3, '열무김치국수': 2, '올챙이만두국': 2, '호박잎된장찌개': 1, '근대국': 7, '옛날돈까스': 4, '콩나물김치국': 5, '나가사끼짬뽕': 5, '김치국': 2, '꼬지어묵탕': 3, '맑은장국': 1, '김치국수': 2, '토란탕': 1, '배추국': 1, '새알미역국': 1, '올갱이아욱국': 2, '황태무채국': 1, '옛날왕돈까스': 3, '대구매운탕': 3, '홍합탕': 3, '냉이된장국': 1, '오징어튀김': 1, '버섯매운국': 1, '소고기매운국': 1, '도토리묵냉국': 3, '로제스파게티': 1, '삼계국밥': 1, '완두콩스프': 1, '조랭이떡미역국': 1, '매운소고기국': 1, '호박젓국찌개': 2, '미니우동': 4, '호박새우젓국': 1, '매운쇠고기국': 1, '크림스프': 3, '들깨버섯국': 2, '미니짬뽕': 1, '해물수제비': 2, '민물새우찌개': 1, '들깨시래기국': 3, '팽이가쯔오장국': 1, '쇠고기국': 1, '얼갈이국': 4, '미니잔치국수': 1, '김치순두부찌개': 1, '달래된장국': 1, '꼬지어묵국': 2, '미니햄버거': 1, '매운소고기무국': 1, '떡국': 2, '미니국수': 1, '스프': 1, '두부김치국': 3, '무청된장국': 1, '초계국수': 2, '동태탕': 2, '소고기매운무국': 1, '차돌된장찌개': 1, '시래기들개탕': 1, '브로컬리크림스프': 1, '맑은연두부탕': 1, '북어해장국': 2, '사과오이냉국': 1, '해물짬뽕국': 1, '건새우아욱된장국': 1, '김치어묵국': 2, '황태해장국': 1, '얼큰소고기무국': 1, '떡만두국': 1, '짬뽕국': 3, '만두국': 1, '해물칼국수': 1, '매운콩나물국': 1, '대구탕': 1, '쑥된장국': 1, '칼국수': 1, '나가사키짬뽕국': 1, '물만두국': 1, '해물손수제비': 1, '건새우아욱국': 1, '장각닭죽': 1, '메밀국수': 1, '부대찌개&쫄면사리': 1, '가쓰오장국': 3, '백종원의': 1, '뼈없는감자탕': 1, '두부미소된장국': 1, '굴미역국': 1, '조갯살아욱국': 1, '나가사끼짬뽕국*라면': 1, '감자만두국': 2, '황태미역국': 1, '홍합무우국': 1, '다슬기아욱국': 1, '근대두부된장국': 1, '우삼겹부대찌개': 1, '유부된장국': 1, '전주식콩나물국': 1, '얼큰동태탕': 1, '삼선짬뽕국*칼국수': 1, '모듬어묵탕': 1, '소고기된장찌개': 1, '돼지국밥': 1, '해물순두부국': 1, '스팸김치찌개': 2, '유부주머니된장국': 2, '매운계란파국': 1, '고기짬뽕국': 3, '우동국물': 4, '나박물김치': 1, '만둣국': 1, '추가밥': 1, '참치파개장': 1, '크림스프/추가밥': 1, '짬뽕순두부찌개': 1, '꼬치어묵국': 1, '두부된장찌개': 1, '숙주고기짬뽕': 1, '유부우동국물': 1, '오징어무국': 1, '김치수제비국': 1, '냉메밀소바': 1, '잡채말이어묵국': 1, '유부주머니우동국': 1, '얼큰감자국': 1, '동태매운탕': 1, '우동장국': 1, '매운닭개장': 1, '김밥': 1, '우거지된장국': 1, '매운순대국밥': 1, '어묵매운탕': 1, '우거지국': 1, '사골옹심이만둣국': 1, '컵라면&찐계란': 2, '온모밀국수': 1, '김치어묵탕': 1, '김칫국': 1, '옹심이만둣국': 1, '버섯육개장': 1, '매운순대국': 1, '떡갈비주먹밥/추가밥': 1, '청양콩나물국': 1, '황태국수': 1, '홍합짬뽕국': 1, '맑은콩나물국': 1, '옹심이감자국': 1, '미소된장국': 1, '꼬치어묵매운탕': 1, '손수제비국': 1, '순두부백탕*양념장': 1, '맑은버섯닭개장': 1, '아귀매운탕': 1, '장수제비': 1, '미니쌀국수': 1, '감자양파국': 1, '옹심이국': 1, '맑은버섯국': 1, '순두부백탕': 1, '북어짬뽕국': 1, '미니쫄우동*맛살튀김': 1}

In [19]:
len(dish_cnt)

286